name: GoVulnCheck

on:
  push:
    branches:
      - main

jobs:
  go-vulncheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x # Use the Go version you require

      - name: Install govulncheck
        run: go get github.com/K2InformaticsGmbH/govulncheck

      - name: Run govulncheck
        run: |
          govulncheck -u -c ./govulncheck-config.json
        env:
          GO111MODULE: on
